config/routes.rb
Rails.application.routes.draw do
  put 'cart', to: 'cart#reserve', as: 'reserve'
  resources :seats
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  root "seats#index"
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/cart.rb
class Cart < ApplicationRecord
  has_many :seats
end

app/models/seat.rb
class Seat < ApplicationRecord
  belongs_to :cart, optional: true

  validates :row, :column, :cost, presence: true
  validates :row, :column, numericality: { integer: true }
  validates :cost, numericality: { only_integer: true, greater_than: 0 }

  after_update_commit :broadcast_seat_update

  state_machine :state, initial: :free do
    state :free
    state :selected
    state :reserved


    event :mark_as_free do
      transition %i[selected reserved] => :free
    end

    event :mark_as_selected do
      transition %i[free] => :selected
    end

    event :mark_as_reserved do
      transition %i[selected] => :reserved
    end
  end

  private

  def broadcast_seat_update
    broadcast_replace_to "seats", partial: "seats/seat", locals: { seat: self }
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :set_cart
  before_action :set_render_cart

  private

  def set_cart
    @cart ||= Cart.find_by(id: session[:cart_id])

    if @cart.nil?
      @cart = Cart.create
      session[:cart_id] = @cart.id
    end
  end

  def set_render_cart
    @render_cart = false
  end
end

app/controllers/cart_controller.rb
class CartController < ApplicationController
  def reserve
    ActiveRecord::Base.transaction do
      @cart.seats.each do |seat|
        seat.mark_as_reserved!
      end
    end

    session[:cart_id] = nil

    redirect_to root_path, notice: 'Seats reserved'
  end
end

app/controllers/seats_controller.rb
class SeatsController < ApplicationController
  before_action :set_seat, only: %i[ show edit update destroy ]

  def index
    @seats = Seat.all
  end

  def show
  end

  def new
    @seat = Seat.new
  end

  def edit
  end

  def create
    @seat = Seat.new(seat_params)

    respond_to do |format|
      if @seat.save
        render :show, status: :created, location: @seat
      else
        render :new, status: :unprocessable_entity
      end
    end
  end

  def update
    turbo_stream_actions = []
    return head :ok if @seat.reserved?

    if @seat.free?
      @seat.mark_as_selected!
      @seat.cart = @cart
      turbo_stream_actions << turbo_stream.append('selected_seats', partial: 'seats/cart_item', locals: { seat: @seat })
    elsif @seat.selected? && @seat.cart == @cart
      @seat.mark_as_free!
      @seat.cart = nil
      turbo_stream_actions << turbo_stream.remove(helpers.dom_id(@seat, :cart_item))
    end

    @seat.save

    turbo_stream_actions << turbo_stream.replace("reserve_btn", partial: 'seats/reserve_btn', locals: { count: @cart.seats.count })

    render turbo_stream: turbo_stream_actions.join("\n"), status: :ok
  end

  def destroy
    @seat.destroy

    redirect_to seats_url, notice: "Seat was successfully destroyed."
  end

  private
    def set_seat
      @seat = Seat.find(params[:id])
    end

    def seat_params
      params.require(:seat).permit(:row, :column, :state, :cost, :cart_id)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/cart_helper.rb
module CartHelper
end

app/helpers/seats_helper.rb
module SeatsHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>LetMeSeat</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_include_tag "application", "data-turbo-track": "reload", defer: true %>

    <style>
      <%= ".my-seat-#{session[:cart_id]}" %> {
          background-color: grey !important;
      }
    </style>

    <script type="text/javascript">
      var sessionId = "<%= session[:cart_id] %>";
    </script>
  </head>

  <body>
    <%= yield %>
    <%= render 'cart/cart' if @render_cart%>
  </body>
</html>

app/views/seats/_cart_item.html.erb
<li class="list-group-item d-flex justify-content-between align-items-center" id=<%=dom_id(seat, :cart_item)  %>>
  Seat: <%= seat.id %>
  Cost: <%= seat.cost %>
</li>

app/views/seats/_form.html.erb
<%= form_with(model: seat) do |form| %>
  <% if seat.errors.any? %>
    <div style="color: red">
      <h2><%= pluralize(seat.errors.count, "error") %> prohibited this seat from being saved:</h2>

      <ul>
        <% seat.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div>
    <%= form.label :row, style: "display: block" %>
    <%= form.number_field :row %>
  </div>

  <div>
    <%= form.label :column, style: "display: block" %>
    <%= form.number_field :column %>
  </div>

  <div>
    <%= form.label :state, style: "display: block" %>
    <%= form.text_field :state %>
  </div>

  <div>
    <%= form.label :cost, style: "display: block" %>
    <%= form.number_field :cost %>
  </div>

  <div>
    <%= form.label :cart_id, style: "display: block" %>
    <%= form.text_field :cart_id %>
  </div>

  <div>
    <%= form.submit %>
  </div>
<% end %>

app/views/seats/_reserve_btn.html.erb
<turbo-frame id="reserve_btn" target="_top">
  <%= form_with url: reserve_path, method: :put do %>
      <%= submit_tag 'Reserve', class: "btn btn-primary", disabled: !count.positive? %>
    <% end %>
</turbo-frame>

app/views/seats/_seat.html.erb
<div id="<%= dom_id seat %>">
  <div class="border rounded-circle text-center <%= 'seat-state_' + seat.state %> <%= "my-seat-"+seat.cart_id.to_s if seat.selected? %>" style="width: 40px; height: 40px; line-height: 30px;">
    <%= form_with url: seat_path(seat), method: :put, remote: true do %>
      <%= submit_tag seat.id, class: 'btn btn-link', disabled: seat.reserved?, 'data-action': 'click->cart#update', 'data-seat-state': seat.state, 'data-seat-cost': seat.cost %>
  <% end %>
  </div>
</div>

app/views/seats/edit.html.erb
<h1>Editing seat</h1>

<%= render "form", seat: @seat %>

<br>

<div>
  <%= link_to "Show this seat", @seat %> |
  <%= link_to "Back to seats", seats_path %>
</div>

app/views/seats/index.html.erb
<%= turbo_stream_from "seats"%>

<div class="container">
  <p style="color: green"><%= notice %></p>
  <p style="color: red"><%= alert %></p>
</div>


<div data-controller="cart">
  <div class="container">
    <h1>Seats</h1>
    <div id="seats">
      <% @seats.group_by(&:row).sort.each do |row, seats_in_row| %>
        <div class="d-flex justify-content-start mb-3">
          <% seats_in_row.sort_by(&:column).each do |seat| %>
            <div class="p-2"><%= render "seat", seat:, updater_id: @cart.id %> </div>
          <% end %>
        </div>
      <% end %>
    </div>
  </div>

  <div class="container">
    <h2>Cart</h2>
    <ul class="list-group mt-3">
      <turbo-frame id="selected_seats">
        <% @cart.seats.sort.each do |seat| %>
          <%= render "cart_item", seat: %>
        <% end %>
      </turbo-frame>

    </ul>
    <div>
      <p>Total: <span data-cart-target="total"><%= @cart.seats.sum(&:cost) %></span></p>
    </div>
  </div>
</div>

<div class="container">
    <%= render "reserve_btn", count: @cart.seats.count %>
</div>

app/views/seats/new.html.erb
<h1>New seat</h1>

<%= render "form", seat: @seat %>

<br>

<div>
  <%= link_to "Back to seats", seats_path %>
</div>

app/views/seats/show.html.erb
<p style="color: green"><%= notice %></p>

<%= render @seat %>

<div>
  <%= link_to "Edit this seat", edit_seat_path(@seat) %> |
  <%= link_to "Back to seats", seats_path %>

  <%= button_to "Destroy this seat", @seat, method: :delete %>
</div>